export const formDataLanguage = [
  {
    language: {
      mongolian: {
        part1: {
          title: "Байгууллагын мэдээлэл",
          inputLabel1: "Байгууллагын нэр /Кирилээр/",
          inputPholder1: "Байгууллага А",
          inputLabel2: "Байгууллагын нэр /Латинаар/",
          inputLabel3: "Байгууллагын рег. дугаар",
          inputPholder3: "Регистрийн  дугаар",
          inputLabel4: "Үйл ажиллагааны чиглэл",
          inputPholder4: "Чиглэл",
          inputLabel5: "Захирал/ Байгууллагын утас",
          inputPholder5: "Байгууллагын утас ( Заавал биш )",
          inputLabel6: "Нягтлан бодогчийн утас",
          inputPholder6: "Утасны дугаараа оруулна уу",
          inputLabel7: "Имэйл",
          inputPholder7: "Имэйлээ оруулна уу",
          inputLabel8: "Хаяг",
          inputPholder8: "Хаягаа оруулна уу",
        },
        part2: {
          title: "1-р гарын үсэг / ",
          titleText: "Гэрээний нүүрэн дээр бичигдэх",
          inputLabel1: "Албан тушаал",
          inputPholder1: "Гүйцэтгэх захирал...",
          inputPholder2: "Овог Нэр",
        },
        part3: {
          title: "2-р гарын үсэг",
          inputLabel1: "Албан тушаал",
          inputPholder1: "Менежер, Нягтлан бодогч, Инженер ...",
          inputPholder2: "Овог Нэр",
        },
        part4: {
          title: "Гэрээний мэдээлэл",
          inputLabel1: "Авах хэрэглэгчийн тоо",
          inputLabel2: "Нэмэлт бааз/компани авах эсэх",
          inputPholder2: "Сонгох",
          yes: "Тийм",
          no: "Үгүй",
        },
        part5: {
          textAreaLabel1:
            "Тайлбар /Нэмэлт бааз авах бол компанийн нэр, РД оруулна уу/",
          textAreaLabel2: "Системийн талаарх мэдээллийг хаанаас авсан бэ?",
          buttonText: "Илгээх",
        },
      },
      english: {
        part1: {
          title: "Company information",
          inputLabel1: "Name of the organization /in Kyril/",
          inputPholder1: "Company A",
          inputLabel2: "Name of the organization /in Latin/",
          inputLabel3: "Company reg. no",
          inputPholder3: "Register number",
          inputLabel4: "Areas of activity",
          inputPholder4: "Areas",
          inputLabel5: "Director/ Company Tel",
          inputPholder5: "Company phone (optional)",
          inputLabel6: "Accountant phone number",
          inputPholder6: "Enter your phone number",
          inputLabel7: "Email",
          inputPholder7: "Enter you email",
          inputLabel8: "Address",
          inputPholder8: "Enter your address",
        },
        part2: {
          title: "Signature 1 /",
          titleText: "To be written on the face of the contract",
          inputLabel1: "Position",
          inputPholder1: "Executive Director...",
          inputPholder2: "Name",
        },
        part3: {
          title: "Signature 2",
          inputLabel1: "Position",
          inputPholder1: "Manager, Accountant, Engineer...",
          inputPholder2: "Name",
        },
        part4: {
          title: "Contract information",
          inputLabel1: "Number of users to get",
          inputLabel2: "Whether to get additional bases/companies",
          inputPholder2: "Choose",
          yes: "Yes",
          no: "No",
        },
        part5: {
          textAreaLabel1:
            "Note / To get additional camp, please enter company name and RD/",
          textAreaLabel2: "Where did you get the information about the system?",
          buttonText: "Send",
        },
      },
    },
  },
];
